apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-secrets
  namespace: nginx-demo
spec:
  provider: azure
  parameters:
    keyvaultName: kv-tflocal
    tenantId: <tenant-id> # az account show --query tenantId -o tsv
    clientID: <managed-identity-client-id>
    objects: |
      array:
        - |
          objectName: connection-string
          objectType: secret