apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-secrets
  namespace: nginx-demo
spec:
  provider: azure
  parameters:
    keyvaultName: kv-tflocal
    tenantId: de0e38a2-f749-41b0-867d-3ecb26a00ac6
    clientID: 77f4f8f3-380b-45b0-9b2a-460b6a655efb
    objects: |
      array:
        - |
          objectName: connection-string
          objectType: secret